# Dependencies
markdown:         kramdown
highlighter:         null

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
name:            Me Love You Runtime
title:            Me Love You Runtime
tagline:          Code Monkey!
description:      Me Love You Runtime
url:              http://blog.meloveyourunti.me

author:
  name:           Francis Gilbert
  url:            https://twitter.com/frangilbert

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/poole
  
sass:
  sass_dir:          _sass
  style:            :compressed

gems:
  - jekyll-paginate
  - jekyll-gist