# Dependencies
markdown:         redcarpet
pygments:         false

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
name:            Me Love You Runtime
title:            Me Love You Runtime
tagline:          Code Monkey!
description:      Me Love You Runtime
url:              http://blog.meloveyourunti.me

author:
  name:           Francis Gilbert
  url:            https://twitter.com/frangilbert

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
