# Dependencies
markdown:         redcarpet
pygments:         false

# Permalinks
permalink:        /:year/:month/:day/:title

# Setup
title:            Me Love You Runtime
tagline:          'Code Monkey!'
description:      ''
url:              http://frangilbert.github.io/meloveyouruntime/

author:
  name:           'Francis Gilbert'
  url:            https://twitter.com/frangilbert

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
